name: 'Validation / Coding Standards [v4]'

on:
  pull_request:
    branches:
      - release/4.0.0
    paths:
      - '**.php'
      - '**.js'
      - '**.scss'
      - 'phpcs.xml*'
      - '.stylelintrc*'
      - '.eslintrc*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Composer Install
        run: composer install --prefer-dist --optimize-autoloader

      - name: Install dependencies
        run: composer lint

  css:
    runs-on: ubuntu-latest
    name: CSS
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint:css

  js:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint:js
